export { default as Home } from "./HomeLayout";
export { default as About } from "./About";
export { default as Plants } from "./Plants";
export { default as Error } from "./Error";
export { default as PrivateRoute } from "./PrivateRoute";
export { default as Cart } from "./Cart";
export { default as SinglePlant } from "./SinglePlant";
export { default as HomeLayout } from "./HomeLayout";
export { default as Landing } from "./Landing";
